### ISSUE TITLE
ModuleNotFoundError: No module named 'sensor_msgs'

### ISSUE THREAD

**Issue by Rothschild-hhu** [zhaoxuhui/ROS-Bag-Tools#1]
I am sorry to bother you, it is my first time to use ros. I have installed all the needed dependencies according to 'parseBag.py'. When I run the `python parseBag.py 2021-12-18-20-05-55.bag`  in the terminal. I meet the following problem:

> Traceback (most recent call last):
>   File "parseBag.py", line 6, in <module>
>     from cv_bridge import CvBridge
>   File "./Softwares/anaconda3/envs/slam/lib/python3.6/site-packages/cv_bridge/__init__.py", line 1, in <module>
>     from .core import CvBridge, CvBridgeError
>   File "./Softwares/anaconda3/envs/slam/lib/python3.6/site-packages/cv_bridge/core.py", line 34, in <module>
>     import sensor_msgs.msg
> ModuleNotFoundError: No module named 'sensor_msgs'

My environment is as follows：

- OS with Version: Linux Ubuntu 18.04
- rosbag&rospy：1.15.11 
- pyparsing：2.4.7
- cv-bridge ：1.13.0
- opencv-contrib-python：3.4.2.17

At the same time, when I run the ‘saveOdometry.py’, I also encountered similar problems. It looks like missing module named xxxx.msg.

So can you give me some suggestions to solve the problem? Thanks a lot!

**Comment by zhaoxuhui** [comment]
It seems that you used a wrong version python to run the script. As the error messge says /Softwares/anaconda3/envs/slam/lib/python3.6 can not find the library. 

Things usually get difficult if you have ROS and anacodna on your system. When you installed the ROS, some related libraries are installed to system default python, not anaconda python. So if you use anaconda python to run the script, you may get import errors.

The solution is easy: you can try to run the script with system default python rather than anaconda python.

For how to switch ROS python environments and anaconda, you may refer to this [blog](http://zhaoxuhui.top/blog/2021/02/20/slam-environment-installation-log.html) for more information. Generally, write some paths in .bashrc file and comment some lines according to your goal, like this:
```
# For CUDA
export PATH=$PATH:/usr/local/cuda/bin

# For Anaconda2
export PATH=$PATH:/root/anaconda2/bin

# For ROS
source /opt/ros/kinetic/setup.bash
source ~/Codes/catkin_ws/devel/setup.bash

# For Kalibr
# source ~/Codes/kalibr_workspace/devel/setup.bash
```

**Comment by Rothschild-hhu** [comment]
> It seems that you used a wrong version python to run the script. As the error messge says /Softwares/anaconda3/envs/slam/lib/python3.6 can not find the library.
> 
> Things usually get difficult if you have ROS and anacodna on your system. When you installed the ROS, some related libraries are installed to system default python, not anaconda python. So if you use anaconda python to run the script, you may get import errors.
> 
> The solution is easy: you can try to run the script with system default python rather than anaconda python.
> 
> For how to switch ROS python environments and anaconda, you may refer to this [blog](http://zhaoxuhui.top/blog/2021/02/20/slam-environment-installation-log.html) for more information. Generally, write some paths in .bashrc file and comment some lines according to your goal, like this:
> 
> ```
> # For CUDA
> export PATH=$PATH:/usr/local/cuda/bin
> 
> # For Anaconda2
> export PATH=$PATH:/root/anaconda2/bin
> 
> # For ROS
> source /opt/ros/kinetic/setup.bash
> source ~/Codes/catkin_ws/devel/setup.bash
> 
> # For Kalibr
> # source ~/Codes/kalibr_workspace/devel/setup.bash
> ```

I‘m really glad to receive your reply. In fact, it is caused by the different versions of Python just as you said. According to your suggestion, I run the script using the system default python and it works. But I have a question, when I run "python --version" in terminal, it shows 2.7.17, so is the script written in python2.x? 

Finally, thank you for uploading these codes. They are very useful and convenient. At the same time, I also benefited a lot from your [blog](http://zhaoxuhui.top/). It gave me a lot of inspiration. Send my best wishes to you.

**Comment by zhaoxuhui** [comment]
Generally, the script runs normally in python2 & python3 environment. If not, it you can write here and reopen this issue.

**Comment by Rothschild-hhu** [comment]
> Generally, the script runs normally in python2 & python3 environment. If not, it you can write here and reopen this issue.

Ok.  Thank you again.
