### ISSUE TITLE
No such file or directory: 'rosbag': 'rosbag'

### ISSUE THREAD

**Issue by kirk0306** [zhaoxuhui/ROS-Bag-Tools#3]
感谢您写的脚本！不过在使用的时候遇到一些问题：
似乎是subprocess的问题，执行到`subprocess.Popen(['rosbag', 'info', '--yaml', bag_path], stdout=subprocess.PIPE).communicate()[0])`会提示

  File "changeBagFramerate.py", line 47, in <module>

    name_list, framerate_list,num_list,end_timestamp, duration = getFramerateInfo(bag_path)

  File "changeBagFramerate.py", line 8, in getFramerateInfo

    subprocess.Popen(['rosbag', 'info', '--yaml', bag_path], stdout=subprocess.PIPE).communicate()[0],Loader = yaml.FullLoader)

  File "/home/mm/anaconda3/envs/notebook/lib/python3.7/subprocess.py", line 800, in __init__

    restore_signals, start_new_session)

  File "/home/mm/anaconda3/envs/notebook/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

`FileNotFoundError: [Errno 2] No such file or directory: 'rosbag': 'rosbag'`

正常import rosbag是可以使用的，请问是我使用脚本的方法有问题吗？

**Comment by kirk0306** [comment]
找到原因了，pip直接安装rosbag是不行的，需要用这个：
`pip install rosbag --extra-index-url https://rospypi.github.io/simple/`

**Comment by mengxyokok** [comment]
vscode会自动加env环境变量，jetbrains不会加，如果vscode可以运行，大概率是jetbrains的环境变量设置问题
